# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 1e91e92623bb784fba1e32aebd5ae8dd77de7268b7df14388d92289aa833523a49a5270c621cebfcc6b912e3f12a366d34deca1f02d109133de1f450a3f3efdf

test:
  secret_key_base: 62b584dd13e5329392c79c87b0d74dfd26388289d13574924ad18bcec011eeaa3538bbe5d76da5233631265c890dc014cc82720ad201675e35eb95f78f308f44

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
